// This file will be auto-generated by TanStack Router
// For now, we'll create a basic route tree manually

import { createRootRoute, createRoute, Outlet } from '@tanstack/react-router';
import { RootLayout } from './layouts/RootLayout';
import { AppLayout } from './layouts/AppLayout';
import { AuthPage } from './routes/auth';
import { HomePage } from './routes/home';
import { ChatPage } from './routes/chat';
import { NotesPage } from './routes/notes';
import { PromptsPage } from './routes/prompts';
import { SettingsPage } from './routes/settings';
import { ConnectionsPage } from './routes/connections';

// Root route with layout
const rootRoute = createRootRoute({
  component: RootLayout,
});

// Auth route (no app layout)
const authRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/auth',
  component: AuthPage,
});

// App layout route (authenticated)
const appRoute = createRoute({
  getParentRoute: () => rootRoute,
  id: '_app',
  component: AppLayout,
});

// Home route (new chat)
const homeRoute = createRoute({
  getParentRoute: () => appRoute,
  path: '/',
  component: HomePage,
});

// Chat route
const chatRoute = createRoute({
  getParentRoute: () => appRoute,
  path: '/c/$chatId',
  component: ChatPage,
});

// Notes route
const notesRoute = createRoute({
  getParentRoute: () => appRoute,
  path: '/notes',
  component: NotesPage,
});

// Prompts route
const promptsRoute = createRoute({
  getParentRoute: () => appRoute,
  path: '/workspace/prompts',
  component: PromptsPage,
});

// Settings route
const settingsRoute = createRoute({
  getParentRoute: () => appRoute,
  path: '/settings',
  component: SettingsPage,
});

// Connections route
const connectionsRoute = createRoute({
  getParentRoute: () => appRoute,
  path: '/workspace/connections',
  component: ConnectionsPage,
});

// Build the route tree
export const routeTree = rootRoute.addChildren([
  authRoute,
  appRoute.addChildren([homeRoute, chatRoute, notesRoute, promptsRoute, settingsRoute, connectionsRoute]),
]);
