// This file will be auto-generated by TanStack Router
// For now, we'll create a basic route tree manually

import { createRootRoute, createRoute } from '@tanstack/react-router';
import { RootLayout } from './layouts/RootLayout';
import { AppLayout } from './layouts/AppLayout';
import { AuthPage } from './routes/auth';
import { SSOCallbackPage } from './routes/auth-sso-callback';
import { HomePage } from './routes/home';
import { ChatPage } from './routes/chat';
import { NotesPage } from './routes/notes';
import { PromptsPage } from './routes/prompts';
import { LandingPage } from './routes/landing';

// Root route with layout
const rootRoute = createRootRoute({
  component: RootLayout,
});

// Landing page at / (public)
const landingRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: LandingPage,
});

// Auth route (login/signup)
const authRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/auth',
  component: AuthPage,
});

// SSO callback route (no app layout)
const ssoCallbackRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/auth/sso-callback',
  component: SSOCallbackPage,
});

// App layout route (authenticated) - all app routes under /app
const appRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/app',
  component: AppLayout,
});

// Dashboard/Home route (new chat) - /app
const homeRoute = createRoute({
  getParentRoute: () => appRoute,
  path: '/',
  component: HomePage,
});

// Chat route - /app/c/:chatId
const chatRoute = createRoute({
  getParentRoute: () => appRoute,
  path: '/c/$chatId',
  component: ChatPage,
});

// Notes route - /app/notes
const notesRoute = createRoute({
  getParentRoute: () => appRoute,
  path: '/notes',
  component: NotesPage,
});

// Prompts route - /app/prompts
const promptsRoute = createRoute({
  getParentRoute: () => appRoute,
  path: '/prompts',
  component: PromptsPage,
});

// Build the route tree
export const routeTree = rootRoute.addChildren([
  landingRoute,
  authRoute,
  ssoCallbackRoute,
  appRoute.addChildren([homeRoute, chatRoute, notesRoute, promptsRoute]),
]);
