// Active plan catalog. These plans are seeded into the billing `plans` table
// and exposed via billing.getPlans.
export const planData = [
  {
    id: "free",
    name: "Free",
    description: "Encrypted AI chat to get started",
    tier: 0,
    monthlyPrice: 0,
    yearlyPrice: 0,
    inferenceRequestsLimit: 100,
    byokInferenceRequestsLimit: 500,
    storageLimitMb: 1000,
    maxEnclaves: 0,
    features: {
      voiceCalls: true,
      voiceInput: true,
      prioritySupport: false,
      dedicatedEnclaves: false,
      customEndpoints: true,
      largeModels: false,
      priorityQueue: false,
    },
    dodoPriceIdMonthly: null,
    dodoPriceIdYearly: null,
  },
  {
    id: "starter",
    name: "Starter",
    description: "Private AI for everyday use",
    tier: 1,
    monthlyPrice: 1200,
    yearlyPrice: 12000,
    inferenceRequestsLimit: 500,
    byokInferenceRequestsLimit: 2000,
    storageLimitMb: 2000,
    maxEnclaves: 0,
    features: {
      voiceCalls: true,
      voiceInput: true,
      prioritySupport: false,
      dedicatedEnclaves: false,
      customEndpoints: true,
      largeModels: true,
      priorityQueue: false,
    },
    dodoPriceIdMonthly: "pdt_0NY6luwJk4UoMIhsO1mMe",
    dodoPriceIdYearly: "pdt_0NY6lxXewtV9yLxjq8Yzl",
  },
  {
    id: "pro",
    name: "Pro",
    description: "Serious privacy for serious work",
    tier: 2,
    monthlyPrice: 2900,
    yearlyPrice: 27600,
    inferenceRequestsLimit: 5000,
    byokInferenceRequestsLimit: -1,
    storageLimitMb: 20000,
    maxEnclaves: 0,
    features: {
      voiceCalls: true,
      voiceInput: true,
      prioritySupport: false,
      dedicatedEnclaves: true,
      customEndpoints: true,
      largeModels: true,
      priorityQueue: false,
    },
    dodoPriceIdMonthly: "pdt_0NY6NccyasPmnImIkbocM",
    dodoPriceIdYearly: "pdt_0NY6Nj9gnxfrsiUrxrlI1",
  },
  {
    id: "team",
    name: "Team",
    description: "Encrypted AI for your organization",
    tier: 4,
    monthlyPrice: 3500,
    yearlyPrice: 39600,
    inferenceRequestsLimit: 5000,
    byokInferenceRequestsLimit: -1,
    storageLimitMb: 20000,
    maxEnclaves: -1,
    features: {
      voiceCalls: true,
      voiceInput: true,
      prioritySupport: true,
      dedicatedEnclaves: true,
      customEndpoints: true,
      largeModels: true,
      priorityQueue: true,
    },
    dodoPriceIdMonthly: "pdt_0NY6Nqvklb7ueLbSB4FCz",
    dodoPriceIdYearly: "pdt_0NY6O27jrS1W7Xfz9PLma",
  },
];
