// Temporarily unlimited free plan while we wait for Dodo Payments live access.
// Paid plans (starter, pro, privacy_max, team) are commented out and will be
// re-enabled once payment processing is live.
export const planData = [
  {
    id: "free",
    name: "Free",
    description: "Encrypted AI chat — all features included",
    tier: 0,
    monthlyPrice: 0,
    yearlyPrice: 0,
    inferenceRequestsLimit: -1, // unlimited
    byokInferenceRequestsLimit: -1, // unlimited
    storageLimitMb: -1, // unlimited
    maxEnclaves: -1, // unlimited
    features: {
      voiceCalls: true,
      voiceInput: true,
      prioritySupport: false,
      dedicatedEnclaves: true,
      customModels: true,
      customEndpoints: true,
      largeModels: true,
      priorityQueue: false,
    },
    dodoPriceIdMonthly: null,
    dodoPriceIdYearly: null,
  },
  // --- Paid plans disabled until Dodo Payments live account is active ---
  // {
  //   id: "starter",
  //   name: "Starter",
  //   description: "Private AI for everyday use",
  //   tier: 1,
  //   monthlyPrice: 1200,
  //   yearlyPrice: 12000,
  //   inferenceRequestsLimit: 500,
  //   byokInferenceRequestsLimit: 2000,
  //   storageLimitMb: 2000,
  //   maxEnclaves: 0,
  //   features: {
  //     voiceCalls: true,
  //     voiceInput: true,
  //     prioritySupport: false,
  //     dedicatedEnclaves: false,
  //     customModels: false,
  //     customEndpoints: true,
  //     largeModels: true,
  //     priorityQueue: false,
  //   },
  //   dodoPriceIdMonthly: "pdt_0NY6luwJk4UoMIhsO1mMe",
  //   dodoPriceIdYearly: "pdt_0NY6lxXewtV9yLxjq8Yzl",
  // },
  // {
  //   id: "pro",
  //   name: "Pro",
  //   description: "Serious privacy for serious work",
  //   tier: 2,
  //   monthlyPrice: 2900,
  //   yearlyPrice: 27600,
  //   inferenceRequestsLimit: 5000,
  //   byokInferenceRequestsLimit: -1,
  //   storageLimitMb: 20000,
  //   maxEnclaves: 0,
  //   features: {
  //     voiceCalls: true,
  //     voiceInput: true,
  //     prioritySupport: false,
  //     dedicatedEnclaves: true,
  //     customModels: false,
  //     customEndpoints: true,
  //     largeModels: true,
  //     priorityQueue: false,
  //   },
  //   dodoPriceIdMonthly: "pdt_0NY6NccyasPmnImIkbocM",
  //   dodoPriceIdYearly: "pdt_0NY6Nj9gnxfrsiUrxrlI1",
  // },
  // {
  //   id: "privacy_max",
  //   name: "Privacy Max",
  //   description: "Maximum privacy, zero compromise",
  //   tier: 3,
  //   monthlyPrice: 4900,
  //   yearlyPrice: 46800,
  //   inferenceRequestsLimit: -1,
  //   byokInferenceRequestsLimit: -1,
  //   storageLimitMb: 100000,
  //   maxEnclaves: -1,
  //   features: {
  //     voiceCalls: true,
  //     voiceInput: true,
  //     prioritySupport: true,
  //     dedicatedEnclaves: true,
  //     customModels: true,
  //     customEndpoints: true,
  //     largeModels: true,
  //     priorityQueue: true,
  //   },
  //   dodoPriceIdMonthly: "pdt_0NY6mBbYf6BwIo4YKhsrH",
  //   dodoPriceIdYearly: "pdt_0NY6mGr6afu5TvwTnrhiL",
  // },
  // {
  //   id: "team",
  //   name: "Team",
  //   description: "Encrypted AI for your organization",
  //   tier: 4,
  //   monthlyPrice: 3500,
  //   yearlyPrice: 39600,
  //   inferenceRequestsLimit: 5000,
  //   byokInferenceRequestsLimit: -1,
  //   storageLimitMb: 20000,
  //   maxEnclaves: -1,
  //   features: {
  //     voiceCalls: true,
  //     voiceInput: true,
  //     prioritySupport: true,
  //     dedicatedEnclaves: true,
  //     customModels: true,
  //     customEndpoints: true,
  //     largeModels: true,
  //     priorityQueue: true,
  //   },
  //   dodoPriceIdMonthly: "pdt_0NY6Nqvklb7ueLbSB4FCz",
  //   dodoPriceIdYearly: "pdt_0NY6O27jrS1W7Xfz9PLma",
  // },
];
